name: Actions para Docker-Compose

on: push

jobs:

  dockerhub_push:

    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest

  deploy:

    needs: dockerhub_push

    permissions:
      contents: write
      pages: write     
      id-token: write  
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: configure github pages
        uses: actions/configure-pages@v3

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v4
        with: 
          path: "."

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1